on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: docker image to be deployed

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
      - run: >
          helm upgrade ${{ github.event.repository.name }}-prod ./chart
          --install --atomic --timeout 300s
          --create-namespace -n ${{ github.event.repository.name }}
          --set image=${{ inputs.image }}
          --set git.revision="${{ github.sha }}"
          --set git.version="${{ github.run_id }}"
          --set secret.SPEEDPORT_PASSWORD="${{ secrets.SPEEDPORT_PASSWORD }}"
          # add more secrets if needed
