on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  containerize:
    uses: ./.github/workflows/.containerize.yml
    permissions:
      contents: read
      packages: write
  deploy:
    needs:
      - containerize
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      image: ${{ needs.containerize.outputs.image }}
